<a href="https://colab.research.google.com/github/IsraaMohamedGaber/PyTorch-Study/blob/main/Study_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**what is the tensor?**

A tensor is a mathematical object used in many areas of science and engineering, especially in physics and machine learning. It generalizes scalars, vectors, and matrices to higher dimensions.

Here's a simple breakdown:

Scalar: A single number (0-dimensional tensor), e.g., 5

Vector: A list of numbers (1-dimensional tensor), e.g., [1, 2, 3]

Matrix: A 2D array of numbers (2-dimensional tensor), e.g.,

[[1, 2],

 [3, 4]]

ensor: An n-dimensional array of numbers (n-dimensional tensor), e.g.,
A 3D tensor might look like a cube of numbers or a list of matrices.

In machine learning and deep learning, tensors are the core data structures. Libraries like TensorFlow and PyTorch are named after them and use tensors to represent and manipulate data and model parameters.

In physics, tensors describe physical properties that depend on direction, such as stress, strain, and the curvature of spacetime in general relativity.


**Resources**

https://ai.plainenglish.io/what-is-a-tensor-2715746a4785

https://docs.pytorch.org/docs/stable/index.html

https://github.com/pytorch/pytorch

https://www.kaggle.com/datasets/hojjatk/mnist-dataset


this visualize network:
https://tensorspace.org/

In [3]:
import torch
torch.__version__

'2.6.0+cu124'

In [10]:
#scaler
scaler=torch.tensor(6)
scaler, scaler.ndim  #zero-dimision

(tensor(6), 0)

In [11]:
#scaler
scaler=torch.tensor(6)
scaler.item()

6

In [7]:
#how to create vector of tensors
vector=torch.tensor([7,7])
vector, vector.ndim #first order dimnision

(tensor([7, 7]), 1)

In [13]:
#how to create vector of tensors
vector=torch.tensor([7,7])
#vector, vector.ndim, vector.item() => ERROR .item for scalar only


In [15]:
#how to identify the shape of the tensor
vector.shape,scaler.shape
#torch.Size([])) because scaler is zero dimnision

(torch.Size([2]), torch.Size([]))

In [17]:
#matrix
matrix=torch.tensor([[4,7],
                     [5,6]])
matrix, matrix.ndim

(tensor([[4, 7],
         [5, 6]]),
 2)

In [18]:
matrix.shape

torch.Size([2, 2])

In [20]:
#3D Tensor
d3_tensor=torch.tensor([[ [1,2,3],
                          [4,5,6],
                          [7,8,9]]])
d3_tensor,d3_tensor.ndim,d3_tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([1, 3, 3]))

In [22]:
#create random tensor
random_tensor=torch.rand(size=(4,3))
random_tensor

tensor([[0.3062, 0.7074, 0.2218],
        [0.0030, 0.9332, 0.5022],
        [0.6560, 0.1977, 0.6296],
        [0.7841, 0.0134, 0.4695]])

In [23]:
random_tensor.shape ,random_tensor.ndim

(torch.Size([4, 3]), 2)

In [24]:
scaler

tensor(6)

In [26]:
#check the shape
vector,vector.ndim

(tensor([7, 7]), 1)

#data type of tensor
https://docs.pytorch.org/docs/stable/tensors.html

In [27]:
random_tensor.dtype

torch.float32

In [29]:
x_tensor=torch.rand(size=(5,4,4,3))
x_tensor.ndim

4

In [30]:
x_tensor=torch.rand(size=(4,4,3))
x_tensor.ndim

3

RGB= [red , green , blue]

In [31]:
x_tensor=torch.rand(size=(224,224,3))
x_tensor.ndim

3

In [32]:
# zeros tensor
zero_tensor=torch.zeros(size=(2,2,8))
zero_tensor,zero_tensor.shape,zero_tensor.ndim,zero_tensor.dtype

(tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]]]),
 torch.Size([2, 2, 8]),
 3,
 torch.float32)

In [33]:
#ones tensor
ones_tensor=torch.ones(size=(2,2,8))
ones_tensor,ones_tensor.shape,ones_tensor.ndim,ones_tensor.dtype

(tensor([[[1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1.]]]),
 torch.Size([2, 2, 8]),
 3,
 torch.float32)

In [37]:
#arange => this function take start and end and step
t_tensor=torch.range(start=0,end=10,step=1)
t_tensor

<ipython-input-37-15495369ce93>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  t_tensor=torch.range(start=0,end=10,step=1)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
#arange => this function take start and end and step
t_tensor=torch.arange(start=0,end=10,step=1)
t_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
r_tensor =torch.tensor(data=[4,5,7],
                       dtype=torch.float32,
                       device=None,
                       #requires_grad=True #=> meaning record operation ocuur on tensor
                       requires_grad=False#=> # Desfault value
                       )
r_tensor ,r_tensor.dtype,r_tensor.device

(tensor([4., 5., 7.]), torch.float32, device(type='cpu'))

In [45]:
# tensor operations
# 1. multiply
# 2. addition
# 3. subtraction
# 4. division

In [53]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [54]:
x=x+10
x

tensor([11, 12, 13])

In [55]:
x=x-2
x

tensor([ 9, 10, 11])

In [56]:
x = x*2
x

tensor([18, 20, 22])

In [57]:
x = x / 2
x

tensor([ 9., 10., 11.])

In [58]:
y = x * x
y

tensor([ 81., 100., 121.])

In [59]:
x=torch.multiply(x,10)
x

tensor([ 90., 100., 110.])

In [60]:
x = torch.matmul(x,x) #dot product retuen scalar
x

tensor(30200.)

In [62]:
x.shape ,x.ndim

(torch.Size([]), 0)

In [63]:
tensor_a=torch.rand(size=(2,3))
tensor_a,tensor_a.shape

(tensor([[0.5018, 0.2060, 0.6747],
         [0.3230, 0.2696, 0.1421]]),
 torch.Size([2, 3]))

In [64]:
tensor_b=torch.rand(size=(2,3))
tensor_b,tensor_b.shape

(tensor([[0.4021, 0.3295, 0.5165],
         [0.5054, 0.6096, 0.6883]]),
 torch.Size([2, 3]))

In [66]:
#tensor_f=torch.matmul(tensor_a,tensor_b)
#tensor_f,tensor_f.shape

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [67]:
tensor_f=torch.matmul(tensor_a,tensor_b.T)
tensor_f,tensor_f.shape

(tensor([[0.6181, 0.8436],
         [0.2921, 0.4254]]),
 torch.Size([2, 2]))

In [68]:
tensor_a=torch.rand(size=(2,3))
tensor_a,tensor_a.shape

(tensor([[0.0648, 0.9227, 0.4901],
         [0.2153, 0.4810, 0.7276]]),
 torch.Size([2, 3]))

In [69]:
tensor_b=torch.rand(size=(3,2))
tensor_b,tensor_b.shape

(tensor([[0.9729, 0.7340],
         [0.1511, 0.1069],
         [0.3266, 0.3434]]),
 torch.Size([3, 2]))

In [70]:
tensor_f=torch.matmul(tensor_a,tensor_b)
tensor_f,tensor_f.shape

(tensor([[0.3626, 0.3145],
         [0.5198, 0.4593]]),
 torch.Size([2, 2]))

In [73]:
random_tensor_a=torch.rand(size=(2,3))
random_tensor_a
#generate random numbers

tensor([[0.7779, 0.4716, 0.0635],
        [0.2645, 0.0387, 0.2644]])

In [76]:
#manual seed genaration
torch.manual_seed(42)
random_tensor_b=torch.rand(size=(2,3))
random_tensor_b
#to control number  generated by ran using manual seed

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

https://docs.pytorch.org/docs/stable/generated/torch.nn.Linear.html

In [77]:
from torch import nn

In [81]:
linear_layer =nn.Linear(in_features=6,out_features=4) # now layef is 6 x 4 => scond order
tensor_L=torch.rand(size=(4,7))
x=linear_layer(tensor_L)
x

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x7 and 6x4)

In [82]:
linear_layer =nn.Linear(in_features=6,out_features=4) # now layef is 6 x 4 => scond order
tensor_L=torch.rand(size=(4,6))
x=linear_layer(tensor_L)
x

tensor([[-0.3311, -0.2694, -0.3352, -0.3260],
        [-0.1316, -0.1841, -0.6096, -0.3276],
        [-0.3114,  0.0419, -0.4256, -0.5528],
        [-0.0243,  0.2167, -0.7545, -0.5736]], grad_fn=<AddmmBackward0>)

In [83]:
 v = torch.arange(0,10,1)
 v

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
v.min()

tensor(0)

In [85]:
v.max()

tensor(9)

In [86]:
 v = torch.arange(0,16,2)
 v

tensor([ 0,  2,  4,  6,  8, 10, 12, 14])

In [87]:
v.min() #return value

tensor(0)

In [88]:
v.max()  #return value

tensor(14)

In [89]:
max_index =v.argmax() #return index
max_index

tensor(7)

In [90]:
min_index =v.argmin() #return index
min_index

tensor(0)

In [92]:
float_tensor=torch.arange(0.,10.,1.)
float_tensor,float_tensor.dtype

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [93]:
float_tensor=torch.arange(0,10,1)
float_tensor,float_tensor.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)